
export enum Category{
    WEB_DEVELOPMENT="WEB_DEVELOPMENT",
    DIGITAL_MARKETING="DIGITAL_MARKETING",
    GRAPHIC_DESIGN="GRAPHIC_DESIGN",
    CONSULTING="CONSULTING",
    MOBILE_APP_DEVELOPMENT="MOBILE_APP_DEVELOPMENT",
    CLOUD_SOLUTIONS="CLOUD_SOLUTIONS",
    COMPUTER_HARDWARE="COMPUTER_HARDWARE", 
    SOFTWARE="SOFTWARE",          
    ELECTRONICS="ELECTRONICS",      
    FURNITURE="FURNITURE"
    }